#!/usr/bin/env bash

mkdir "$@"/home/web; cp static-site/docs.udon "$@"/home/web
rm -rf "$@"/home/web/docs
cp -r static-site/docs "$@"/home/web/docs
cp static-site/index.hoon "$@"/home/web.hoon rm -rf "$@"/home/ren/partials
cp -r partials "$@"/home/ren/partials
cp urb.hoon "$@"/home/ren
exit
