#!/usr/bin/env bash

rm -rf "$@"/home/web/posts
echo posts
mkdir "$@"/home/web/posts; cp -r static-site/posts "$@"/home/web/posts
cp -r static-site/{images,assets,css,js} "$@"/home/web
cp static-site/index.hoon "$@"/home/web.hoon
cp static-site/*.hoon "$@"/home/web
rm -rf "$@"/home/ren/partials
cp -r partials "$@"/home/ren/partials
cp urb.hoon "$@"/home/re
exit
